# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Offense count: 108
Metrics/AbcSize:
  Max: 298

# Offense count: 53
Metrics/BlockNesting:
  Max: 8

# Offense count: 14
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1985

# Offense count: 106
Metrics/CyclomaticComplexity:
  Max: 71

# Offense count: 136
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 435

# Offense count: 3
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 425

# Offense count: 8
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 11

# Offense count: 98
Metrics/PerceivedComplexity:
  Max: 86

# Offense count: 8
Lint/Loop:
  Exclude:
    - 'src/clients/sw_single.rb'
    - 'src/include/packager/key_manager_dialogs.rb'
    - 'src/lib/packager/clients/repositories.rb'
    - 'src/modules/InstShowInfo.rb'

# Offense count: 3
Style/AccessorMethodName:
  Exclude:
    - 'src/modules/SourceManager.rb'
    - 'src/modules/SpaceCalculation.rb'

# Offense count: 17
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts.
Style/FileName:
  Enabled: false

# Offense count: 473
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/MethodName:
  Enabled: false

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'src/modules/Packages.rb'

# Offense count: 148
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/VariableName:
  Enabled: false

# Offense count: 10
# Configuration parameters: SupportedStyles.
# SupportedStyles: snake_case, normalcase, non_integer
Style/VariableNumber:
  Enabled: false
