language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools yast2-testsuite yast2 yast2-pkg-bindings yast2-storage cheetah abstract_method" -g "rspec:3.3.0 yast-rake simplecov coveralls"
script:
    - sudo rake install
    - COVERAGE=1 rake test:unit
