language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    # install newer augeasget repo with newer augeas, otherwise ruby-augeas fails (see https://github.com/yast/yast-network/pull/454#issuecomment-253795507)
    - sudo add-apt-repository -y ppa:raphink/augeas
    - sudo apt-get update
    - sudo apt-get install libaugeas-dev libxml2-dev
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools yast2-testsuite yast2 yast2-pkg-bindings yast2-country-data yast2-storage ruby2.1-dev libaugeas-dev pkg-config" -g "rspec:3.3.0 yast-rake coveralls cfa cheetah"
script:
    - make -f Makefile.cvs
    - make
    - sudo make install
    - make check
    - COVERAGE=1 rake test:unit

